[package]
name = "repojump"
version = "0.1.0"
description = "A local development project launcher"
authors = ["FarMC"]
edition = "2021"

[lib]
name = "repojump_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
atomic-write-file = "0.3"
dunce = "1"
uuid = { version = "1", features = ["v4"] }
url = "2"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_System_Com", "Win32_UI_Shell", "Win32_UI_Shell_Common"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
panic = "abort"
